### ISSUE TITLE
Boyers Model of Scholarship

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/LDRS591#19]
[LINK](https://create.twu.ca/ldrs591-sp18/unit-1-notes/)

Do we have/need permission?

**Comment by HeatherStrong11** [comment]
Just working on getting the reference for that particular image.  It came from this site: http://sites.stedwards.edu/innovationfellowship/2014/05/28/scholarship-of-teaching-learning-sotl/

**Comment by HeatherStrong11** [comment]
I don't see a copyright indication on this blog.  Should I just state "in the public domain" in the reference?

**Comment by cmadland** [comment]
No, you can’t assume that something is in the public domain. If there is no indication, you should assume that it is copyrighted.

Is there a contact email for the site so we can ask for permission?

Is the image necessary?

Colin
--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
t: 604.513.2121 ext. 3876 | e: colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

On Dec 22, 2017, at 9:02 AM, HeatherStrong11 <notifications@github.com<mailto:notifications@github.com>> wrote:


I don't see a copyright indication on this blog. Should I just state "in the public domain" in the reference?

**Comment by HeatherStrong11** [comment]
Should the reference for this image be:
From "Scholarship of Teaching and Learning (SoTL)," by J. Sievers, 2014 (http://sites.stedwards.edu/innovationfellowship/2014/05/28/scholarship-of-teaching-learning-sotl/). In the public domain.

**Comment by HeatherStrong11** [comment]
I actually don't think the image is necessary at all.  We can remove it.

**Comment by cmadland** [comment]
Based on this reverse image search https://www.google.ca/search?dcr=0&q=boyer%27s+model+of+scholarship&tbm=isch&source=iu&ictx=1&tbs=simg:CAESvwEJRsCPxwSDqxoaswELEKjU2AQaBAgVCAQMCxCwjKcIGmIKYAgDEiiZE5oTwx3LHaMTmxP6B6ITlBOcE8Q-hT3jPeQz1j_11P80_14j3hPcs2GjAEtLL-PrPbC9BX4Q1OMqp88h1txGp8v7rTK49zbwxAqO_1y0DsaHA97LrTA7eL0uO0gBAwLEI6u_1ggaCgoICAESBKD_1fcMMCxCd7cEJGh8KHQoKc2NyZWVuc2hvdNqliPYDCwoJL20vMDF6Ym53DA&fir=RsCPxwSDqxpnnM%253A%252CebWzoN0bESAHLM%252C_&usg=__MBlDNT5jPl4T-wywUOU37JMA5UY%3D&sa=X&ved=0ahUKEwiw1vqYjZ7YAhVBKWMKHROcBJ0Q9QEIPTAC#imgrc=z3nt9hQn0-HkSM:<https://www.google.ca/search?dcr=0&q=boyer's+model+of+scholarship&tbm=isch&source=iu&ictx=1&tbs=simg:CAESvwEJRsCPxwSDqxoaswELEKjU2AQaBAgVCAQMCxCwjKcIGmIKYAgDEiiZE5oTwx3LHaMTmxP6B6ITlBOcE8Q-hT3jPeQz1j_11P80_14j3hPcs2GjAEtLL-PrPbC9BX4Q1OMqp88h1txGp8v7rTK49zbwxAqO_1y0DsaHA97LrTA7eL0uO0gBAwLEI6u_1ggaCgoICAESBKD_1fcMMCxCd7cEJGh8KHQoKc2NyZWVuc2hvdNqliPYDCwoJL20vMDF6Ym53DA&fir=RsCPxwSDqxpnnM%3A%2CebWzoN0bESAHLM%2C_&usg=__MBlDNT5jPl4T-wywUOU37JMA5UY=&sa=X&ved=0ahUKEwiw1vqYjZ7YAhVBKWMKHROcBJ0Q9QEIPTAC#imgrc=z3nt9hQn0-HkSM:>

It seems like the table has been produced in many different formats and we could just cite the original source.


--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
t: 604.513.2121 ext. 3876 | e: colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

On Dec 22, 2017, at 9:07 AM, HeatherStrong11 <notifications@github.com<mailto:notifications@github.com>> wrote:


I actually don't think the image is necessary at all. We can remove it.

**Comment by HeatherStrong11** [comment]
I think we have just removed it.

**Comment by cmadland** [comment]
yup
