### ISSUE TITLE
Reference

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/LDRS591#20]
Penner, D. (2017). INQUIRY 1SS3: Inquiry in the social sciences _[Syllabus]._ Hamilton, ON: McMaster University. Retrieved from [https://socialsciences.mcmaster.ca/…/Inquiry C08 Course Outline 2017](https://socialsciences.mcmaster.ca/…/Inquiry C08 Course Outline 2017)

[LINK](https://create.twu.ca/ldrs591-sp18/unit-1-notes/)

**Comment by HeatherStrong11** [comment]
I'm working on finding a link that works.

**Comment by cmadland** [comment]
It looks like there is just a piece missing and replaced with the ellipsis.

cm


--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
t: 604.513.2121 ext. 3876 | e: colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

On Dec 22, 2017, at 8:37 AM, HeatherStrong11 <notifications@github.com<mailto:notifications@github.com>> wrote:


I'm working on finding a link that works.

**Comment by HeatherStrong11** [comment]
I've updated the link in WordPress and have checked to make sure it works and it does :)
