### ISSUE TITLE
Tables

### ISSUE THREAD

**Issue by cmadland** [TWUOnline/LDRS591#22]
Tables built in TablePress

**Comment by HeatherStrong11** [comment]
Not sure what this means.  Do you want to skype to help me understand what you need me to do?

**Comment by cmadland** [comment]
sounds good



--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
t: 604.513.2121 ext. 3876 | e: colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

On Dec 22, 2017, at 9:08 AM, HeatherStrong11 <notifications@github.com<mailto:notifications@github.com>> wrote:


Not sure what this means. Do you want to skype to help me understand what you need me to do?

**Comment by HeatherStrong11** [comment]
I think I have completed most of them.  I will continue to do this as I am checking unit notes.

**Comment by HeatherStrong11** [comment]
Done!

**Comment by cmadland** [comment]
Are they embedded in the pages with the shortcodes?

**Comment by HeatherStrong11** [comment]
Yes they are (and I even know what you are talking about!)
