### ISSUE TITLE
Timeline

### ISSUE THREAD

**Issue by HeatherStrong11** [TWUOnline/LDRS591#25]
I added information to the Course Timeline Page at the back end of WP.  But couldn't figure out how to remove the information that was in there from 500 course time line.  I have not added hyperlinks to the course assignments on the timeline yet.

**Comment by cmadland** [comment]
right…that’s in the ‘advanced WordPress’ lesson. Sorry.

I’ll update that.


--
Colin Madland, MEd (Distance Education)
Online Learning and Instructional Technologies
Trinity Western University  | 7600 Glover Road
Langley, BC | V2Y 1Y1
t: 604.513.2121 ext. 3876 | e: colin.madland@twu.ca<mailto:colin.madland@twu.ca>
@colinmadland | create.twu.ca<http://create.twu.ca>

On Dec 22, 2017, at 2:40 PM, HeatherStrong11 <notifications@github.com<mailto:notifications@github.com>> wrote:


I added information to the Course Timeline Page at the back end of WP. But couldn't figure out how to remove the information that was in there from 500 course time line. I have not added hyperlinks to the course assignments on the timeline yet.
